<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1gH8QxK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1gH8QxK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1gH8QxK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1gH8QxK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1gH8QxK\App_KernelDevDebugContainer([
    'container.build_hash' => '1gH8QxK',
    'container.build_id' => 'faa45e7f',
    'container.build_time' => 1637703747,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1gH8QxK');
