<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSF3XAfq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSF3XAfq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSF3XAfq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSF3XAfq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSF3XAfq\App_KernelDevDebugContainer([
    'container.build_hash' => 'SF3XAfq',
    'container.build_id' => '433d7fac',
    'container.build_time' => 1637616965,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSF3XAfq');
