<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE6Hn7AI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE6Hn7AI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE6Hn7AI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE6Hn7AI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE6Hn7AI\App_KernelDevDebugContainer([
    'container.build_hash' => 'E6Hn7AI',
    'container.build_id' => '94839c3d',
    'container.build_time' => 1637598545,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE6Hn7AI');
